[package]
name = "mathm-im-already-raytracer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17"
vek = "0.15"
rayon = "1.5"
