[package]
name = "im-already-raytracer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = { version = "0.15", features = ["repr_simd"] }
rayon = "1.5"
rand = "0.8"
rand_distr = "0.4"
